---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8s-nginxapp-sot
  namespace: fluxcdtutorial
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/sahillinux/k8s_nginxapp_sot.git
