apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: fluxcdtutorial
spec:
  encryptedData:
    token: AgB8xla9V9MXIbfWRm4LRsQjoYKO+i8pcYUKpj52F5hwL2k6F76uuiHCMrKlixhqUI79TRpQZQpFH3w3N6M2wUTe5xSjngtZK+/2/bJ/YtJdgtIlNmZvdToYyL78X4Cy03QODBb7GEeocnrjD8G6tbW+XX4jtZvNKh3dt4E7erelVBF2OrwI1xBMuNCHot6NW4T3RuE9h7sz2HrAcljkYUUQSGKKJ4VZ4gVU39ujTt+n2ePjTmDfGLIXviboqort9WhcQ5uecbsYNx3b2r+z7uFQFsDTcj4Xs7+FWu1oQHTnXbfJrIUkoGxS/LNZcI5DnQvbl0bdTsYd88KhnCaGAtvT0WoHdGskG3xXfD4VqicM+HFHyFrdicDp0pcopgqium5FyWg9RebO2zkwgFOrdaecLJdrp5O1Gsxrv0AYLEZo4ZO+5hItBpCHLHKBmS7bDrukHO4umKJjYiK7OhI2FJKgxx4k903YK4dwtFqMDCi7KlY7cnvt8qXpIAt90QCFsTo2w5XNSvPDyTfoGphnuMGQtl+8mrsWUe0HtSlY/IUjEILffEH5QtOdc+4HNacptuF8ezNfRm6a5MZ885owN7RK/91SS7dpxTxhUdkAZ1bUPnU1UCImN27iQaaiqohi5KhkCQSbNMCKhXyooobDoUGWpnZYTtBFBvE6/FSJ2hhwY8mEF5u/EKKBNS2On/VBRdhsQIj3o+7yYrH2U1EJJuniJqgvh8TwR6E2NF4gcOcny3nt0FhPfLhn
  template:
    metadata:
      creationTimestamp: null
      name: github
      namespace: fluxcdtutorial

